using Iterate.Domain.Content;

namespace Iterate.Domain.Progression
{
    /// <summary>
    /// One resolved offer: the content the slot sells, already looked up in the catalog, at the price
    /// the offer or pool membership carries rather than any price on the definition.
    /// </summary>
    /// <param name="OfferIdentity">The offer's identity, authored or generated by a reroll.</param>
    /// <param name="ContentID">The content's identity.</param>
    /// <param name="Category">The content category, which decides how a purchase routes.</param>
    /// <param name="Definition">The frozen definition.</param>
    /// <param name="Price">The Tokens it costs.</param>
    public sealed record ShopSlotOffer(
        string OfferIdentity,
        string ContentID,
        ContentCategory Category,
        ContentDefinition Definition,
        int Price
    );
}